helm fix

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -74,13 +74,13 @@ jobs:
         run: |
           ls -la helm-charts
           ls -la ${{ env.HELM_CHART_PATH }} || echo "node-app directory not found"
-          cat ${{ env.HELM_CHART_PATH }}/Chart.yml || echo "Chart.yml not found"
-          cat ${{ env.HELM_CHART_PATH }}/values.yml || echo "values.yml not found"
+          cat ${{ env.HELM_CHART_PATH }}/Chart.yaml || echo "Chart.yaml not found"
+          cat ${{ env.HELM_CHART_PATH }}/values.yaml || echo "values.yaml not found"
 
       - name: Update Helm Chart
         run: |
           cd ${{ env.HELM_CHART_PATH }}
-          sed -i "s|tag: .*|tag: ${{ github.sha }}|" values.yml
+          sed -i "s|tag: .*|tag: ${{ github.sha }}|" values.yaml
           helm lint .
 
       - name: Commit Helm Chart Updates
@@ -88,6 +88,6 @@ jobs:
           cd helm-charts
           git config user.email "github-actions@github.com"
           git config user.name "GitHub Actions"
-          git add node-app/values.yml
+          git add node-app/values.yaml
           git commit -m "Update image tag to ${{ github.sha }}"
           git push
